"""empty message

Revision ID: 13af43bc16de
Revises: 2400c404b129
Create Date: 2024-06-20 17:15:40.738896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils.custom_types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13af43bc16de'
down_revision: Union[str, None] = '2400c404b129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varieties',
    sa.Column('variety', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('availability')
    op.drop_table('shops')
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('variety_id', sa.UUID(), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'products', 'varieties', ['variety_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'variety_id')
    op.drop_column('products', 'discount')
    op.create_table('shops',
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shops_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('availability',
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='availability_product_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], name='availability_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='availability_pkey')
    )
    op.drop_table('varieties')
    # ### end Alembic commands ###
