"""empty message

Revision ID: 2400c404b129
Revises: 30d559cb01b8
Create Date: 2024-06-19 19:40:26.326279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils.custom_types


# revision identifiers, used by Alembic.
revision: str = '2400c404b129'
down_revision: Union[str, None] = '30d559cb01b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('discount', sa.Integer(), nullable=True))
    op.drop_column('availability', 'price')
    op.add_column('products', sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    op.add_column('availability', sa.Column('price', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_column('availability', 'discount')
    # ### end Alembic commands ###
