"""empty message

Revision ID: dca7a8a54646
Revises: 13af43bc16de
Create Date: 2024-06-20 19:47:42.000095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import utils.custom_types


# revision identifiers, used by Alembic.
revision: str = 'dca7a8a54646'
down_revision: Union[str, None] = '13af43bc16de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
