version: '2.2'

services:
  olive-api:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    command: bash -c "gunicorn app:app_ --workers 1 --worker-class worker.OliveUvicornWorker --bind 0.0.0.0:8022 --forwarded-allow-ips='*' --proxy-headers"
    container_name: olive-api
    restart: unless-stopped
    ports:
      - '8022:8022'
    depends_on:
      - olive-db
    environment:
      - POETRY_GROUP='main'
    volumes:
      - ../src:/code
    env_file:
      - ../.env
    networks:
      - my_network

  olive-db:
    build:
      context: ./dockerfiles/postgresql
    restart: unless-stopped
    container_name: olive-db
    cpu_count: 1
    cpu_percent: 50
    mem_limit: 512m
    volumes:
      - olive-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "olive", "-U", "postgres", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    networks:
      - my_network

volumes:
  olive-data:

networks:
  my_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
